version: "3.8"

services:
  iptv:
    build: .
    container_name: freetv-player
    ports:
      - "8080:80"
    volumes:
      - ~/freetv/playlist:/usr/share/nginx/html/playlist
    restart: unless-stopped